---
- name: Install linuxptp build requirements.
  ansible.builtin.apt:
    name:
      - git
      - build-essential
    state: present
  
- name: Ensure /etc/linuxptp exists.
  ansible.builtin.file:
    path: /etc/linuxptp
    state: directory
    mode: "0755"

- name: Clone linuxptp source.
  ansible.builtin.git:
    repo: "{{ linuxptp_repo }}"
    dest: "/usr/local/src/linuxptp"
    version: "{{ linuxptp_version }}"
  register: linuxptp_src

- name: Build and install linuxptp.
  ansible.builtin.shell:
    cmd: make -j "$(nproc)" && make install
    chdir: "/usr/local/src/linuxptp"
  when: linuxptp_src.changed
  notify: Restart linuxptp services

- name: Install testptp.
  ansible.builtin.import_tasks: testptp.yml

- name: Configure ptp4l.
  ansible.builtin.import_tasks: ptp4l.yml

- name: Configure ts2phc.
  ansible.builtin.import_tasks: ts2phc.yml
