---
- name: Deploy Kernel on Time Server (NTP/PTP)
  hosts: kernel
  become: true
  
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 1800

  tasks:
    - name: Install Kernel.
      ansible.builtin.include_tasks: tasks/kernel.yml