---
- name: Deploy Time Server (NTP/PTP)
  hosts: time
  become: true
  vars_files:
    - config.yml
  
  handlers:
    - name: Include various service handlers.
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 1800

  tasks:
    - name: Configure GPS.
      ansible.builtin.include_tasks: tasks/gps.yml

    - name: Configure chrony.
      ansible.builtin.include_tasks: tasks/chrony.yml

    - name: Configure PTP.
      ansible.builtin.include_tasks: tasks/ptp.yml