---
- name: Validate NIC sync method.
  ansible.builtin.assert:
    that: nic_sync_method in ['ts2phc', 'phc2sys']
    fail_msg: "nic_sync_method must be 'ts2phc' or 'phc2sys'"
  when: ptp_role == 'grandmaster'

- name: Install linuxptp build requirements.
  ansible.builtin.apt:
    name:
      - git
      - build-essential
    state: present

- name: Clone linuxptp source.
  ansible.builtin.git:
    repo: "{{ linuxptp_repo }}"
    dest: "{{ linuxptp_build_location }}"
    version: "{{ linuxptp_version }}"
  register: linuxptp_src

- name: Build and install linuxptp.
  ansible.builtin.shell:
    cmd: make -j "$(nproc)" && make install
    chdir: "{{ linuxptp_build_location }}"
  when: linuxptp_src.changed
  notify:
    - Restart ptp4l
    - Restart ts2phc
    - Restart phc2sys

- name: Copy ts2phc systemd unit file into place.
  ansible.builtin.template:
    src: templates/ptp/ts2phc.service.j2
    dest: /etc/systemd/system/ts2phc.service
    owner: root
    group: root
    mode: 0755
  notify: Restart ts2phc
  when: ptp_role == 'grandmaster'

- name: Ensure ts2phc service is in the correct state.
  ansible.builtin.service:
    name: ts2phc
    state: "{{ ts2phc_service_state }}"
    enabled: "{{ ts2phc_service_enabled }}"
  when: ptp_role == 'grandmaster'

- name: Copy phc2sys systemd unit file into place.
  ansible.builtin.template:
    src: templates/ptp/phc2sys.service.j2
    dest: /etc/systemd/system/phc2sys.service
    owner: root
    group: root
    mode: 0755
  notify: Restart phc2sys

- name: Ensure phc2sys service is in the correct state.
  ansible.builtin.service:
    name: phc2sys
    state: "{{ phc2sys_service_state }}"
    enabled: "{{ phc2sys_service_enabled }}"

- name: Ensure /etc/linuxptp exists.
  ansible.builtin.file:
    path: /etc/linuxptp
    state: directory
    mode: 0755

- name: Add ptp4l configuration.
  ansible.builtin.template:
    src: "templates/ptp/ptp4l.conf.j2"
    dest: "/etc/linuxptp/ptp4l.conf"
    mode: 0644
  notify: Restart ptp4l

- name: Copy ptp4l systemd unit file into place.
  ansible.builtin.template:
    src: templates/ptp/ptp4l.service.j2
    dest: /etc/systemd/system/ptp4l.service
    owner: root
    group: root
    mode: 0755
  notify: Restart ptp4l

- name: Ensure ptp4l service is in the correct state.
  ansible.builtin.service:
    name: ptp4l
    state: "{{ ptp4l_service_state }}"
    enabled: "{{ ptp4l_service_enabled }}"