{
 "title": "GPS",
 "tags": [ "timing" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Fix Mode",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_mode" }
   ]
  },
  {
   "title": "Satellites Used",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_uSat" }
   ]
  },
  {
   "title": "Satellites Seen",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_nSat" }
   ]
  },
  {
   "title": "TDOP (Timing DOP)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_tdop" }
   ]
  },
  {
   "title": "Time Error Est.",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_ept" }
   ]
  },
  {
   "title": "Leap Seconds",
   "type": "stat",
   "gridPos": { "x": 20, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_leapseconds" }
   ]
  },
  {
   "title": "Satellites Seen / Used",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    { "expr": "gpsd_nSat", "legendFormat": "Seen" },
    { "expr": "gpsd_uSat", "legendFormat": "Used" }
   ]
  },
  {
   "title": "Dilution of Precision",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    { "expr": "gpsd_gdop", "legendFormat": "GDOP" },
    { "expr": "gpsd_pdop", "legendFormat": "PDOP" },
    { "expr": "gpsd_hdop", "legendFormat": "HDOP" },
    { "expr": "gpsd_vdop", "legendFormat": "VDOP" },
    { "expr": "gpsd_tdop", "legendFormat": "TDOP" }
   ]
  },
  {
   "title": "Satellite Signal Strength (used in solution)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "gpsd_sat_ss{used=\"True\"}",
     "legendFormat": "PRN {{PRN}}"
    }
   ]
  }
 ]
}