---
- name: Install chrony.
  ansible.builtin.apt:
    name: chrony
    state: present

- name: Remove Ubuntu default NTP sources (sources.d).
  ansible.builtin.file:
    path: /etc/chrony/sources.d/ubuntu-ntp-pools.sources
    state: absent
  notify: Restart chrony

- name: Customize other chrony configuration.
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/chrony/conf.d/{{ item }}"
    mode: 0644
  notify: Restart chrony
  with_items:
    - allow.conf
    - refclock.conf
    - servers.sources

- name: Ensure chrony is running.
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
